# To start the API, please install Docker and Docker Compose and run
# `docker-compose up` in the directory of this file. You can then reach the API
# at http://localhost:3000.

name: aec-2024-skill08-s3-prod

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: 
    
    environment:
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
